title: The AMAZING GITHUB
author: Walz
email: greenrangerltd@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Here I describe my journey in learning GIT and GITHUB.
# social links
twitter_username: Walethrills # DO NOT include the @ character, or else the build will fail!
github_username:  Greenranger-IT # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
